name: PulseTracker Docker
on: push 

jobs:
    build:
        name: Checkout master
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v2
                
        - name: Build
          run: docker build -t ahylton/pulsetracker:0.1 .
