name: PulseTracker DockerHub Push
on: 
  push:
      branches: 
          - master
          - devel
           

jobs:
    build:
        name: Checkout master
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v2
                
        - name: Login
          run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        - name: Build
          run: docker build -t ahylton/pulsetracker:0.1 .
        - name: Push 
          run: docker push ahylton/pulsetracker:0.1
