name: HeartRate Tests
on: [push, pull_request]

jobs:
    build:
        name: Checkout master
        runs-on: ubuntu-16.04
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: '2.7'
            ref: devel
        - name: Install setuptools
          run: sudo apt-get install -y python-setuptools
        - name: Run Unit Test 
          run: sh run_docker.sh
