name: HeartRate Tests
on: [push, pull_request]

jobs:
    build:
        name: Checkout master
        runs-on: ubuntu-16.04
        steps:
        - uses: actions/checkout@v2
          with:
            ref: devel
        - name: Build docker image
          run: ./run_docker.sh
