name: HeartRate Tests
on: [push, pull_request]

jobs:
    build:
        name: Checkout master
        - uses: actions/checkout@v2
          with:
            ref: devel
        name: build
        runs-on: ubuntu-18.04
        steps:
        - name: Build docker image
          run: sh ./run_docker.sh
