name: HeartRate Tests
on: [push, pull_request]

jobs:
    build:
        name: Checkout master
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: '2.7'
            ref: devel
        - name: Install dependencies
          run: make install 
