name: HeartRate Tests
on: [push, pull_request]

jobs:
    build:
        name: Checkout master
        runs-on: ubuntu-16.04
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: '3.5'
            ref: devel
        - name: Install the dependencies
          run: make install
        - name: Install library
          run: make
        - name: Run Unit Test 
          run: make test
