name: HeartRate Docker Push
on: [push]

jobs:
    build:
        name: Checkout master
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v2
      
        - name: Build
          run: docker build -t heartrate:0.1 . 
                
        - name: Login to Github Package Registry
          env:
            DOCKER_USERNAME: x-access-token
            DOCKER_PASSWORD: ${{ secrets.GIT_ACCESS_TOKEN }}
          run: |
           echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin docker.pkg.github.com
        - name: Push Docker image
          run: docker push docker.pkg.github.com/akilhylton/heartrate/ahylton/heartrate:0.1
